### ISSUE TITLE
Palai Auto Grabber

### ISSUE THREAD

**Issue by xKliment** [DominikHerold/PalimPalim#1]
Hello i was interested in asking if you want to develop a Palai Auto Account Grabber the Bot / Program logs into a Account collects the Palai and sends it to the Main account. If you have for example 10Palai Accounts or 100 it could be very useful.

**Comment by DominikHerold** [comment]
Hi @KIiment ,
ATM I do not see any purpose of such an application. Why would you have for example 100 ¶ accounts?

**Comment by xKliment** [comment]
To Farm the Palai because i currently have 450Accounts and people buy palai
for 50 : $0,01 so you can make money by doing nothing!

Am Mo., 15. Apr. 2019 um 15:30 Uhr schrieb Dominik Herold <
notifications@github.com>:

**Comment by DominikHerold** [comment]
Well, I do not think Palai should used for such things.
But feel free to develop this for yourself if you can. But it seems you can't...

**Comment by xKliment** [comment]
Well i tried it but it didn't really work...

Am Mo., 15. Apr. 2019 um 20:04 Uhr schrieb Dominik Herold <
notifications@github.com>:

**Comment by DominikHerold** [comment]
Sorry, but having 400 accounts contradicts in my eyes palais claim
>let‘s make money fair
